version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-network
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db-network
    ports:
      - "3306:3306"

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    ports:
      - "443:443"
    networks:
      - proxy-network
    depends_on:
      - backend

networks:
  backend-network:
  db-network:
  proxy-network:

volumes:
  db_data:
